name: Build/Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.3

      - name: Install Python (only on Windows and macOS)
        if: runner.os != 'Linux'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Setuptools for Python
        run: pip3 install setuptools

      - name: Install dependencies
        working-directory: electron
        run: pnpm install --frozen-lockfile

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: electron
        run: npm run publish
